-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "city" TEXT NOT NULL,
    "serviceType" TEXT NOT NULL,
    "usageIntent" TEXT NOT NULL,
    "budget" TEXT,
    "timeline" TEXT NOT NULL,
    "consent" BOOLEAN NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'new',
    "notes" TEXT,
    "source" TEXT,
    "campaign" TEXT,
    "medium" TEXT,
    "content" TEXT,
    "term" TEXT,
    "referrer" TEXT,
    "formName" TEXT DEFAULT 'main_contact',
    "assignedTo" TEXT,
    "assignedAt" DATETIME,
    "followUpAt" DATETIME,
    "nextAction" TEXT,
    "callOutcome" TEXT,
    "pipelineStatus" TEXT NOT NULL DEFAULT 'new',
    "operatorAccepted" BOOLEAN,
    "activationDate" DATETIME,
    "operatorNotes" TEXT,
    "ipAddress" TEXT,
    "consentTimestamp" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "policyVersion" TEXT DEFAULT '1.0',
    "isDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "duplicateCount" INTEGER NOT NULL DEFAULT 0,
    "originalLeadId" TEXT,
    "lastSubmittedAt" DATETIME,
    "qualityScore" INTEGER NOT NULL DEFAULT 0
);

